vich_uploader:
    db_driver: orm

    mappings: 
        images:
            upload_destination: '%kernel.project_dir%/public/%imagesFile%'
            namer: 'Vich\UploaderBundle\Naming\OrignameNamer'
            uri_prefix: '%imagesFile%'
        imagesLaptop:
            upload_destination: '%kernel.project_dir%/public/%imagesFile%'
            namer: 'Vich\UploaderBundle\Naming\OrignameNamer'
            uri_prefix: '%imagesFile%'
        imagesIpad:
            upload_destination: '%kernel.project_dir%/public/%imagesFile%'
            namer: 'Vich\UploaderBundle\Naming\OrignameNamer'
            uri_prefix: '%imagesFile%'
        imagesPhone:
            upload_destination: '%kernel.project_dir%/public/%imagesFile%'
            namer: 'Vich\UploaderBundle\Naming\OrignameNamer'
            uri_prefix: '%imagesFile%'
