easy_admin:
  entities:
    Articles:
      class: App\Entity\Articles
      resource: 'App\Controller\AdminArticlesController'
      form:
        fields:
          - { type: 'group', icon: 'pencil', label: "Contenu de l'article", css_class: 'col-lg-7'}
          - titre
          - introduction
          - { property: 'content', label: 'Contenu', type: 'text_editor'}
          - { type: 'group', icon: 'cog', label: "Information", css_class: 'col-lg-4'}
          - { property: 'categorie', label: 'Catégorie'}
          - { property: 'tags', label: 'Tags'}
          - { property: 'thumbnailFile', type: 'vich_image', label: 'Image' }
          - { type: 'section', label: 'Etat de publication'}
          - { property: 'is_online', label: 'En ligne', type: 'checkbox'}
      list:
        title: "Liste des articles" 
        fields: 
          - { property: 'id', label: 'N°' }
          - { property: 'isOnline', label: 'En ligne' }
          - { property: 'titre', label: 'Titre' }
          - { property: 'createdAt', label: 'Date de création', format: 'j.m.Y'  }
          - { property: 'updatedAt', label: 'Dernière mise à jour', format: 'j.m.Y'  }
          - { property: 'categorie', label: 'Catégories' }
          - 'tags'
          - { property: 'thumbnail', type: 'image', label: 'Image', base_path: '%articles%' }
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}