easy_admin:
  entities:
    AttachmentClass:
      class: App\Entity\AttachmentClass
      list:
        title: "Liste des classes d'images"
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}