easy_admin:
  entities:
    Categories:
      class: App\Entity\Categories
      list:
        title: "Liste des catégories"
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
      form:
        fields:
          - {property: 'nom'}
          - {property: 'slug'}