easy_admin:
  entities:
    Media:
      class: App\Entity\Media
      list:
        title: "Liste des médias"
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}