easy_admin:
  entities:
    Processus:
      class: App\Entity\Processus
      list:
        title: "Liste des Processus"
        fields: 
          - { property: 'id', label: 'N°' }
          - { property: 'isOnline', label: 'En ligne' }
          - { property: 'titre', label: 'Titre' }
          - { property: 'niveau', label: 'Niveau' }
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}