easy_admin:
  entities:
    Projets:
      class: App\Entity\Projets
      list:
        title: "Liste des projets"
        fields: 
          - { property: 'id', label: 'N°' }
          - { property: 'isOnline', label: 'En ligne' }
          - { property: 'nom', label: 'Nom' }
          - { property: 'createdAt', label: 'Date de création', format: 'j.m.Y'  }
          - { property: 'updatedAt', label: 'Dernière mise à jour', format: 'j.m.Y'  }
          - { property: 'types', label: 'Types' }
          - { property: 'technologie', label: 'Technologie' }
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}