easy_admin:
  entities:
    Tag:
      class: App\Entity\Tag
      templates:
        edit: 'admin/post/edit.html.twig'
      list:
        title: "Liste des tags"
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
      form:
        fields:
          - {property: 'name'}
          - {property: 'slug'}