easy_admin:
  entities:
    Technologie:
      class: App\Entity\Technologie
      list:
        title: "Liste des téchnologies"
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}