easy_admin:
  entities:
    Types:
      class: App\Entity\Types
      list:
        title: "Listre des types"
        fields: 
          - { property: 'id', label: 'N°' }
          - { property: 'nom', label: 'Nom' }
          - { property: 'slug', label: 'Slug' }
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
      form:
        fields:
          - {property: 'nom'}