easy_admin:
  entities:
    Zones:
      class: App\Entity\Zone
      list:
        title: "Liste des zones"
        fields: 
          - { property: 'id', label: 'N°' }
          - { property: 'nom', label: 'Nom' }
          - { property: 'description', label: 'Description' }
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
      form:
        fields:
          - {property: 'nom'}
          - {property: 'description'}